# Generated by Django 3.1.3 on 2020-11-07 01:07

import backend.api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('uri', models.URLField(unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'test'), (1, 'adhoc'), (2, 'scheduled')], default=0, max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('scheduled', models.DateTimeField(default=backend.api.models.default_scheduled)),
                ('started', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data', models.CharField(max_length=256)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testnode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speedtest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
